[package]
name = "twackup"
version = "1.0.0-alpha"
authors = ["DanP"]
edition = "2018"

[dependencies]
memmap = "0.7.0"
num_cpus = "1.13.0"
threadpool = "1.8.1"
clap = "3.0.0-beta.1"
ansi_term = "0.12"
tar = "0.4.29"
flate2 = { version = "1.0.16", features = ["zlib"], default-features = false }
