[package]
name = "twackup"
version = "1.0.0-alpha"
description = "Simple DEB rebuilding utility for iOS and Debian-based platforms"
authors = ["DanP"]
edition = "2018"
publish = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
debug = 0

[package.metadata.deb]
maintainer = "DanP"
section = "utility"
priority = "optional"
assets = [
    ["build/twackup", "/usr/bin/", "755"],
]

[dependencies]
memmap = "^0.7"
num_cpus = "^1.13"
threadpool = "^1.8"
clap = "3.0.0-beta.1"
ansi_term = "^0.12"
tar = "^0.4"
ar = "^0.8"
flate2 = { version = "^1.0", features = ["zlib"], default-features = false }
indicatif = "^0.15"

[patch.crates-io]
termios = { git = "https://github.com/danpashin/termios-rs", branch = "feature/ios" }
