[package]
name = "twackup"
version = "1.0.0-alpha"
authors = ["DanP"]
edition = "2018"

[dependencies]
memmap = "^0.7"
num_cpus = "^1.13"
threadpool = "^1.8"
clap = "3.0.0-beta.1"
ansi_term = "^0.12"
tar = "^0.4"
ar = "^0.8"
flate2 = { version = "^1.0", features = ["zlib"], default-features = false }
indicatif = "^0.15"
