[package]
name = "twackup"
version = "1.0.0-a3"
description = "Safe and fast iOS utility for rebuilding DEB's and backing up packages"
authors = ["DanP"]
edition = "2018"
publish = false

[package.metadata.deb_pkg]
name = "Twackup (CLI)"
identifier = "ru.shaddy.twackup"
section = "Utilities"
priority = "optional"
architecture = "iphoneos-arm"
depends = "firmware (>= 3.0)"
changelog = "changelog"
homepage = ""
assets = [
    ["build/twackup-ios", "/usr/bin/twackup"],
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
debug = 0

[dependencies]
memmap = "^0.7"
threadpool = "^1.8"
clap = "3.0.0-beta.1"
ansi_term = "^0.12"
tar = "^0.4"
ar = "^0.8"
nix = "^0.18"
flate2 = { version = "^1.0", features = ["zlib"], default-features = false }
indicatif = "^0.15"
gethostname = "^0.2"
chrono = "^0.4"
deque = "^0.3"
num_cpus = "^1.13"
serde_any = { version = "^0.5", default-features = false, features = ["yaml", "toml", "json"] }
serde = { version = "^1.0", features = ["derive"] }
libproc = {git = "https://github.com/danpashin/libproc-rs", branch = "ios", default-features = false }
plist = { version = "^1.0", default-features = false }

[patch.crates-io]
termios = { git = "https://github.com/danpashin/termios-rs", branch = "feature/ios" }
