[env]
ARTIFACTS_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/artifacts"
ARTIFACTS_ROOTLESS_DIR = "${ARTIFACTS_DIR}/rootless"
ARTIFACTS_ROOTFULL_DIR = "${ARTIFACTS_DIR}/rootfull"

[tasks.build-cli-package]
workspace = false
env = { "CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS" = ["twackup-cli"] }
run_task = { name = "create-package", fork = true }

[tasks.build-lib-package]
workspace = false
env = { "CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS" = ["twackup"] }
run_task = { name = "create-package", fork = true }

[tasks.build-gui-package]
workspace = false
command = "cargo"
args = [
    "make",
    "--cwd", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/twackup-gui",
    "create-package"
]

[tasks.create-artifacts-dir]
command = "mkdir"
args = ["-p", "${ARTIFACTS_ROOTLESS_DIR}", "${ARTIFACTS_ROOTFULL_DIR}"]

[tasks.build-all]
workspace = false
dependencies = [
    "create-artifacts-dir",
    "test",
    "build-cli-package",
    "build-lib-package",
    "build-gui-package"
]
