[config]
default_to_workspace = false

[env]
CARGO_MAKE_CRATE_VERSION = { script = ["xcrun xcodebuild -showBuildSettings | grep MARKETING_VERSION | tr -d 'MARKETING_VERSION ='"] }
GUI_ARCHIVE_PATH = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/Twackup.xcarchive"
GUI_APP_DIR = "${GUI_ARCHIVE_PATH}/Products/Applications/Twackup.app"

DEB_NAME = "Twackup (GUI)"
DEB_IDENTIFIER = "ru.danpashin.twackup-gui"
DEB_SECTION = "Utilities"
DEB_PRIORITY = "optional"
DEB_ARCHITECTURE = "iphoneos-arm"
DEB_DEPENDS = "firmware (>= 14.0)"
DEB_CHANGELOG_FILE = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/changelog"
DEB_HOMEPAGE = "https://moreinfo.thebigboss.org/moreinfo/depiction.php?file=twackupDp"
DEB_AUTHOR = "DanP"
DEB_LICENSE = "GPL-3.0-only"
DEB_DESCRIPTION = "Safe and fast GUI utility for rebuilding DEBs and backing up packages"

[tasks.archive]
command = "xcrun"
args = [
    "xcodebuild",
    "clean",
    "archive",
    "-archivePath", "${GUI_ARCHIVE_PATH}",
    "-scheme", "Twackup",
    "-workspace", "Twackup.xcworkspace",
    "CODE_SIGN_IDENTITY=",
    "CODE_SIGNING_REQUIRED="
]

[tasks.sign]
command = "ldid"
args = [ "-S${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/entitlements.plist", "${GUI_APP_DIR}" ]

[tasks.create-deb]
cwd = "${ARTIFACTS_OUTPUT_DIR}"
command = "bundle"
args = [
    "exec", "fpm",
    "--input-type", "dir",
    "--output-type", "deb",
    "--force",
    "--prefix", "${DEB_PREFIX}",
    "--deb-no-changelog",
    "--log", "warn",
    "--name", "${DEB_IDENTIFIER}",
    "--category", "${DEB_SECTION}",
    "--depends", "${DEB_DEPENDS}",
    "--architecture", "${DEB_ARCHITECTURE}",
    "--maintainer", "${DEB_AUTHOR}",
    "--deb-priority", "${DEB_PRIORITY}",
    "--description", "${DEB_DESCRIPTION}",
    "--version", "${CARGO_MAKE_CRATE_VERSION}",
    "--license", "${DEB_LICENSE}",
    "--vendor", "",
    "--deb-changelog", "${DEB_CHANGELOG_FILE}",
    "--url", "${DEB_HOMEPAGE}",
    "--deb-field", "Name: ${DEB_NAME}",

    "${GUI_APP_DIR}=/Applications",
    "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/changelog=/usr/share/doc/${DEB_IDENTIFIER}/changelog",
]

[tasks.create-rootfull-deb]
env = { "DEB_ARCHITECTURE" = "iphoneos-arm", "DEB_PREFIX" = "", "ARTIFACTS_OUTPUT_DIR" = "${ARTIFACTS_ROOTFULL_DIR}" }
run_task = "create-deb"

[tasks.create-rootless-deb]
env = { "DEB_ARCHITECTURE" = "iphoneos-arm64", "DEB_PREFIX" = "/var/jb", "ARTIFACTS_OUTPUT_DIR" = "${ARTIFACTS_ROOTLESS_DIR}" }
run_task = "create-deb"

[tasks.create-ipa]
script = """
working_dir=$(realpath ${GUI_APP_DIR}/../../)
mv "$working_dir/Applications" "$working_dir/Payload"
cd "$working_dir"
zip -r "${ARTIFACTS_DIR}/Twackup-${CARGO_MAKE_CRATE_VERSION}.ipa" Payload
mv "$working_dir/Payload" "$working_dir/Applications"
"""

[tasks.create-package]
dependencies = ["archive", "sign"]
run_task = { name = ["create-rootfull-deb", "create-rootless-deb", "create-ipa"] }
