[env]
CARGO_BUILD_RELEASE_ARG = { value = "--release", condition = { profiles = ["release"] } }
RUSTFLAGS = "--remap-path-prefix=${HOME}="
TWACKUP_FAT_BINARY = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/${CARGO_MAKE_PROJECT_NAME}"
IPHONEOS_DEPLOYMENT_TARGET = "7.0"

DEB_NAME = "Twackup (CLI)"
DEB_IDENTIFIER = "ru.danpashin.twackup"
DEB_SECTION = "Utilities"
DEB_PRIORITY = "optional"
DEB_DEPENDS = "firmware (>= 3.0)"
DEB_CHANGELOG_FILE = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/changelog"
DEB_HOMEPAGE = "https://moreinfo.thebigboss.org/moreinfo/depiction.php?file=twackupDp"
DEB_AUTHOR = "DanP"

[tasks.build-apple-aarch64]
command = "cargo"
toolchain = "${CARGO_MAKE_RUST_DEFAULT_TOOLCHAIN}"
args = ["build", "@@remove-empty(CARGO_BUILD_RELEASE_ARG)", "--target", "aarch64-apple-ios"]

[tasks.build-apple-armv7]
command = "cargo"
toolchain = "nightly"
args = [
    "build",
    "@@remove-empty(CARGO_BUILD_RELEASE_ARG)",
    "--target", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/assets/armv7-apple-ios.json",
    "-Z", "build-std",
]

[tasks.build-fat-binary]
dependencies = ["build-apple-aarch64", "build-apple-armv7"]
command = "lipo"
args = [
    "-create",
    "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/aarch64-apple-ios/${CARGO_MAKE_CARGO_PROFILE}/${CARGO_MAKE_PROJECT_NAME}",
    "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/armv7-apple-ios/${CARGO_MAKE_CARGO_PROFILE}/${CARGO_MAKE_PROJECT_NAME}",
    "-o",
    "${TWACKUP_FAT_BINARY}",
]

[tasks.sign-binary]
command = "ldid"
args = ["-S", "${TWACKUP_FAT_BINARY}"]

[tasks.create-deb]
cwd = "${ARTIFACTS_OUTPUT_DIR}"
command = "bundle"
args = [
    "exec", "fpm",
    "--input-type", "dir",
    "--output-type", "deb",
    "--force",
    "--prefix", "${DEB_PREFIX}",
    "--deb-no-changelog",
    "--log", "warn",
    "--name", "${DEB_IDENTIFIER}",
    "--category", "${DEB_SECTION}",
    "--depends", "${DEB_DEPENDS}",
    "--architecture", "${DEB_ARCHITECTURE}",
    "--maintainer", "${DEB_AUTHOR}",
    "--deb-priority", "${DEB_PRIORITY}",
    "--description", "${CARGO_MAKE_CRATE_DESCRIPTION}",
    "--version", "${CARGO_MAKE_CRATE_VERSION}",
    "--license", "${CARGO_MAKE_CRATE_LICENSE}",
    "--vendor", "",
    "--url", "${DEB_HOMEPAGE}",
    "--deb-field", "Name: ${DEB_NAME}",
    "${TWACKUP_FAT_BINARY}=/usr/bin/twackup",
    "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/COPYING=/usr/share/doc/${DEB_IDENTIFIER}/LICENSE",
    "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/changelog=/usr/share/doc/${DEB_IDENTIFIER}/changelog",
]

[tasks.create-rootfull-deb]
env = { "DEB_ARCHITECTURE" = "iphoneos-arm", "DEB_PREFIX" = "", "ARTIFACTS_OUTPUT_DIR" = "${ARTIFACTS_ROOTFULL_DIR}" }
run_task = "create-deb"

[tasks.create-rootless-deb]
env = { "DEB_ARCHITECTURE" = "iphoneos-arm64", "DEB_PREFIX" = "/var/jb", "ARTIFACTS_OUTPUT_DIR" = "${ARTIFACTS_ROOTLESS_DIR}" }
run_task = "create-deb"

[tasks.create-package]
dependencies = ["build-fat-binary", "sign-binary"]
run_task = { name = ["create-rootfull-deb", "create-rootless-deb"] }
